#if !canImport(ObjectiveC)
    import XCTest

    extension OneSignalTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__OneSignalTests = [
            ("testExample", testExample),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(OneSignalTests.__allTests__OneSignalTests),
        ]
    }
#endif
